# Generated by Django 4.1.6 on 2023-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_menuitem_lunch_menuitem_lunch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='lunch',
        ),
        migrations.AddField(
            model_name='weekday',
            name='lunch',
            field=models.ManyToManyField(blank=True, null=True, related_name='weekday', to='main.lunch'),
        ),
    ]
