# Generated by Django 4.1.6 on 2023-02-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_weekday_lunch_weekday_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='lunch',
            field=models.ManyToManyField(related_name='weekday', to='main.lunch'),
        ),
    ]
