# Generated by Django 4.1.6 on 2023-02-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_menuitem_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=255, unique=True),
        ),
    ]
