# Generated by Django 4.1.6 on 2023-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_weekday_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='weekday', to='main.lunch'),
        ),
    ]
