# Generated by Django 4.1.6 on 2023-02-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_menuitem_price_alter_weekday_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weekday',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.weekday'),
            preserve_default=False,
        ),
    ]
