# Generated by Django 4.1.6 on 2023-02-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_category_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=100000, max_digits=1000),
        ),
    ]
