# Generated by Django 4.1.6 on 2023-02-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='lunch',
            field=models.ManyToManyField(blank=True, null=True, related_name='menuitem', to='main.lunch'),
        ),
    ]
