# Generated by Django 4.1.6 on 2023-02-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_menuitem_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekday',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000000, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=255),
        ),
    ]
