# Generated by Django 4.1.6 on 2023-02-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_weekday_datetime_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
