# Generated by Django 4.1.6 on 2023-02-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_menuitem_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='lunch',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='lunch',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='menuitem', to='main.lunch'),
            preserve_default=False,
        ),
    ]
