# Generated by Django 4.1.6 on 2023-02-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_menuitem_lunch_menuitem_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='date',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='menuitems', to='main.weekday'),
            preserve_default=False,
        ),
    ]
