# Generated by Django 4.1.6 on 2023-02-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_menuitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='lunch',
        ),
    ]
