# Generated by Django 4.1.6 on 2023-02-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_weekday_lunch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='order',
            name='menuitem',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='main.menuitem'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='lunch',
        ),
    ]
