# Generated by Django 4.1.6 on 2023-02-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_order_unique_together_order_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=1000),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'menuitem', 'weekday')},
        ),
    ]
